import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { renderIconSvg } from '../lambda/panel/html';

// One-off: renders the SVG mark to a 180 px PNG for iOS home screens using macOS Quick Look.
const dir = mkdtempSync(join(tmpdir(), 'valheim-icon-'));
const svgPath = join(dir, 'icon.svg');
writeFileSync(svgPath, renderIconSvg());
execFileSync('qlmanage', ['-t', '-s', '180', '-o', dir, svgPath], { stdio: 'ignore' });
const png = readFileSync(join(dir, 'icon.svg.png')).toString('base64');
writeFileSync(
  join(__dirname, '..', 'lambda', 'panel', 'icon.ts'),
  `// Generated by scripts/render-icon.ts from renderIconSvg(). Run it again when the icon changes.\nexport const ICON_180_PNG_BASE64 =\n  '${png}';\n`,
);
console.log(`wrote lambda/panel/icon.ts (${png.length} base64 chars)`);
